public/sites/default/local.services.yml
public/sites/default/local.settings.php

How to test:
1. Checkout branch
2. run `drush cr`
Afterwards you should be able to see twig template info when you open Inspect element.
Caches should be disabled by default. You should see css, tpl and JS changes after reloading page.
You should be able to use `{{ dump(variable_name) }}` inside twig templates for debugging. More info: https://www.drupal.org/docs/theming-drupal/twig-in-drupal/discovering-and-inspecting-variables-in-twig-templates

IFU-000: Add settings for local development

---

conf/cmi/core.extension.yml
conf/cmi/pathauto.pattern.page_content_pattern.yml
conf/cmi/pathauto.settings.yml
public/modules/custom/infofinland_common/infofinland_common.info.yml
public/modules/custom/infofinland_common/infofinland_common.module
public/modules/custom/infofinland_common/infofinland_common.tokens.inc

Add new module for common custom code
Add new token for generating full english paths.
**How to test**
```
make build
make shell
drush en infofinland_common
drush cim -y
drush cr
```
Go to a page in different language than english that has parents in menu tree. Save it. Check that every part of url after language prefix is in english.

New module for custom tokens

---

conf/cmi/views.view.content.yml
public/sites/default/settings.php

A previous changeset broke the content listing admin UI view. This should fix it. 
To test, run `cim` and `cr` kind of stuff and check /admin/content
This fix was based on this thread: https://www.drupal.org/project/drupal/issues/2917327#comment-15032240
Confirmed, last year they removed Somali language and added Ukraine. So this was it.

IFU-858 - fixing error

---

conf/cmi/views.view.content.yml

Acceptance criteria:
https://helsinkisolutionoffice.atlassian.net/browse/IFU-874
- As an admin, go to the content list and verify that the filters work and the language filter is not on two lines.

IFU-874 - fixed the search field on the content page

---

public/modules/custom/infofinland_brokenlink_checker/src/Plugin/QueueWorker/BrokenLinkQueueProcessor.php

The ticket can be found below:
[IFU-859](https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/IFU/boards/198?modal=detail&selectedIssue=IFU-859)
Then run the following commands, git pull and drush cr.
What this ticket or fix does, it fixes one of the logical errors on the broken link checkers source code.
To test this, you should first enable the dblog module and run the cron (multiple times) and then see the results of the cron run on dblog. Now the results should be more reasonable. Another thing that you can check is the linkkipankki page, where you can see which broken links are marked as true and false. After cron run, the true values should be decreasing and the false values should be increasing.  
[IFU-859]: …

IFU-859: Fix the logical error on the source code

---

conf/cmi/linkit.linkit_profile.helfi.yml
public/modules/custom/infofinland_common/infofinland_common.module

Limited the autocomplete for linkit and menu items to only landing pages and basic pages.
To test:
- Try to add a link to a piece of content using CKeditor and verify that the list of suggestions includes only landing pages and basic pages (e.g. Swedish Language Courses is a linkkipankki link and shouldn't appear)
- Rinse and Repeat for menu items

IFU-591 - limited the autocomplete for linkit and menu items

---

conf/cmi/environment_indicator.switcher.stage.yml
public/sites/default/env.indicator.settings.php

First run the following commands, `drush cr` , `drush cim -y` and `drush cr` again.
Basically you don't need to test this, just check that the url's have changed. The right url at the moment is, `https://edit-infofinland.stage.hel.ninja`

IFU-893: hotfix/IFU-893: Changed the url for stage env

---

public/modules/custom/infofinland_gdpr/src/EventSubscriber/InfofinlandGdprSubscriber.php

This PR refers to this ticket [IFU-909](https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/IFU/boards/198/backlog?selectedIssue=IFU-909).
During the php unit tests, I discovered that there was a bug/typo on the custom `infofinland_gdpr` module.
There was error on the namespace of the `InfofinlandGdprSubscriber.php` file, because `Infofinland_gdpr` should be all on lower case, so I fixed that and the unit test started to work with out the `RuntimeException: Case mismatch between loaded and declared class names` error.
[IFU-909]: https://helsinkisolutionoffice.atlassian.net/browse/IFU-909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix/IFU-909: Fixed a typo on infofinland_gdpr custom module

---

conf/cmi/smtp.settings.yml

Like the [IFU-913](https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/IFU/boards/198/backlog?selectedIssue=IFU-913) ticket says we need to change the old SMTP server address, because they are shutting down the server.  The ticket it self tells us to change [ema.hel.fi](http://ema.hel.fi/) to [relay.hel.fi](http://relay.hel.fi/), because that's the new server. The deadline is that these changes should be made at, November the 3rd. 
What seemed a bit odd, is that the current server address that we had on Drupal, had an address of `ema.platta-net.hel.fi` and not `ema.hel.fi`, so basically I hope that the new server address also works for us. Although the current address is different, it seems to work, because we got the request to change the SMTP server address.
To test …

IFU-913: Changed the SMTP server address

---

composer.json
composer.lock
conf/cmi/anonymous_login.settings.yml
conf/cmi/core.extension.yml

This ticket refers to [IFU-904](https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/IFU/boards/198?selectedIssue=IFU-904). The problem was that anonymous users can see the content from the backend. So I installed and enabled new module, that should prevent that. So the content is only visible to logged in users. 
To test this, run the following commands, `composer install` , `drush cim -y` and `drush cr`.
So basically you don't have to be even logged in, but you probably are with Chrome, but try for example Safari (see that you're not logged in) and go to your local ddev url for this project. It should now redirect you to the login page. 
I also test this with my local, if I create a dummy user and try to login from that login form, that it's actually works. Edit: the …

IFU-904: Installed and enabled the anonymous_login module

---

composer.json
composer.lock
conf/cmi/anonymous_login.settings.yml
conf/cmi/core.extension.yml

Reverse the changes, I made yesterday. 
You can run the following commands, if needed, `composer install` , `drush cim` and `drush cr` .
But what this basically do is to remove the `anonymous_login` module from `drupal`, so there is not so much to test, because that didn't work as expected.

IFU-904: Removed the installed module, because it messed up the FE

---

composer.json
composer.lock
conf/cmi/core.extension.yml
conf/cmi/eu_cookie_compliance.settings.yml

This is a test to see, if this fixes the following error and to see, if it fixes the 504 timeout error.
`User warning: The following theme is missing from the file system: eu_cookie_compliance in Drupal\Core\Extension\ExtensionPathResolver->getPathname() (line 63 of core/lib/Drupal/Core/Extension/ExtensionPathResolver.php).`
The banner itself is not enabled, because it needs styling and I thought it would be wise to test it first if it fixes even one of those errors.

IFU-932: Install and enable EU Cookie compliance, banner is hidden, because it needs styling

---

.github/workflows/artifact.yml
.github/workflows/test.yml.dist
.github/workflows/update-config.yml

Restore the workflow drupal-php-docker image versions to 8.2 instead of 8.1.

IFU-925: Restore the drupal-php-docker image versions to 8.2

---

composer.json
composer.lock

This is a workaround for bug: https://www.drupal.org/project/drupal/issues/3285657
The patch ensures that EntityChangedConstraintValidator::validate passes if the database has revisions that are published after the current translation was last edited. This can happen with content_moderation module when moderation status is changed form "Draft" -> "Published".
How to replicate:
- Create Finnish basic page (https://drupal-infofinland.docker.so/fi/node/add/page), set “Save as: Published”
- Edit the Finnish page, set “Save as: Draft”
- Add English translation, set “Save as: Published”.
- Attempt to publish the Finnish draft. You should see error: “The content has either been modified by another user, or you have already submitted modifications. As a result, your changes cannot be saved.” …

UHF-9633: Fix EntityChangedConstraintValidator failing on some nodes

---

public/sites/default/settings.php
public/themes/custom/infofinland_admin/src/css/styles.css

- Fixed node edit page sidebar overflow
- Missing environment indicator configurations added to settings.php
* `git checkout UHF-X_node_sidebar_overflow_fix`
* `make fresh`
- Check node edit form sidebar
- Check environment indicator color

UHF-X D10 fixes

---

public/modules/custom/helfi_ckeditor/helfi_ckeditor.module

Better checks
Ckeditor alignment fix
* `git checkout UHF-X_ckeditor_header_fix`
* `make fresh`
- Go edit any content page in arabic.
- CKeditor content should be aligned RTL
- Header should be aligned LTR

Better checks on ckeditor fix, ckeditor header fix

---

conf/cmi/core.extension.yml
public/modules/custom/infofinland_user_cancel/infofinland_user_cancel.info.yml
public/modules/custom/infofinland_user_cancel/infofinland_user_cancel.module
public/modules/custom/infofinland_user_cancel/tests/src/Functional/UserCancelNodeRevisionsTest.php
public/modules/custom/infofinland_user_cancel/tests/src/Kernel/UserCancelNodeRevisionsTest.php

Adds a new module that invokes the `user_cancel` hook to reassign node revisions to anonymous with a simpler db queries. This bypasses the `node_mass_update` calls which seem to cause issues when there are too many revisions.
Relies on the module being invoked the `node` module. Currently works because this is before in alphabetical order, but might need to use module weight if the order changes in the future.
* Use the `dev` branch and make sure it is up-to-date: `git checkout dev`
* Run `make fresh`
* Try canceling UID 82: https://drupal-infofinland.docker.so/fi/user/82/edit
* This should take a very long time (about 2 hours). Check that the process is going slowly by waiting for a few minutes and cancel the process
* `git …

UHF-9770: Reassign node revisions to anonymous in database before canceling user.

---

conf/cmi/config_ignore.settings.yml
conf/cmi/simple_oauth.settings.yml
conf/cmi/ultimate_cron.job.simple_oauth_cron.yml
public/modules/custom/infofinland_common/infofinland_common.install
public/sites/default/all.settings.php

* Fix out of memory issues when Drupal tries to handle oauth tokens.
* `git checkout UHF-X-out-of-memory-error`
* `make fresh`

UHF-X: Remove expired oauth2 tokens

---

public/modules/custom/infofinland_common/infofinland_common.module

Some of the older entities cannot be found by entity reference field's autocomplete.
Sort the entity reference autocomplete by title length to ensure that all results are reachable
- Go to edit any page with Link bank-paragraph added to it
- Try to add "Neuvonta" -link to the linkbank
- Autocomplete won't offer "Neuvonta" as result.
* `git checkout UHF-9953_links`
* `make fresh`
- Go to edit any page with Link bank-paragraph added to it
- Try to add "Neuvonta" -link to the linkbank
Autocomplete will give you results sorted by title length, including "Neuvonta". 
[UHF-9953]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …

UHF-9953: Sort the autocomplete result by title length.

---

public/modules/custom/infofinland_admin_tools/infofinland_admin_tools.module

Language switcher on node edit shows wrong languages in specific scenario.
Use latest revision of node when altering language switcher
- Setup the site
- Log in as admin
- Go edit node 39579
- Select finnish as language
- Check the language switcher active links
- Should not represent the actual node translations 
- Select any other language (Russian for example)
- Language switcher active links should change
- Should now show the language swithcer active links correctly 
* `git checkout UHF-10175`
* `make fresh`
- Log in as admin
- Go edit node 39579
- All language switcher links should be active on finnish
- Language switcher should show same result for every translation.  
[UHF-10175]: …

UHF-10175 language switcher bug

---

conf/cmi/language/ar/webform.webform.contact.yml
conf/cmi/language/es/webform.webform.contact.yml
conf/cmi/language/et/webform.webform.contact.yml
conf/cmi/language/fa/webform.webform.contact.yml
conf/cmi/language/fi/webform.webform.contact.yml
conf/cmi/language/fr/webform.webform.contact.yml
conf/cmi/language/ru/webform.webform.contact.yml
conf/cmi/language/sv/webform.webform.contact.yml
conf/cmi/language/tr/webform.webform.contact.yml
conf/cmi/language/uk/webform.webform.contact.yml
conf/cmi/webform.webform.contact.yml
conf/cmi/webform.webform.infofinland_contact.yml
public/modules/custom/infofinland_common/infofinland_common.module

Our automatic updates want to add translations to default contact form since it is included in webform/config/install. The translations override important webform handler settings.
See: 1b366e5ae0237455420d92d1c336126d6449b95e.
This patch copies `webform.webform.config` to `webform.webform.infofinland_config` so we can manage translations ourselves.
* Prevent automatic updates from overriding contact form handlers. 
* Add new webform `infofinland_contact`
* Archive webform `contact`
* `git checkout UHF-10062-config-fixes`
* `make up shell`
* Link to other PR
[UHF-10062]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …

UHF-10062: config fixes

---

composer.json
composer.lock

Upgraded the patches
* `git checkout UHF-10603_fix_patches`
* `make fresh`
* Setup frontend
run yarn 
run yarn build
build process should finish without completely dying (Done in xx.yy s.)
/fi/sitemap page should load

UHF-10603: old patches broke sitemap SSR

---

composer.json

Yoast SEO plugin was throwing error at page load, causinge aggregated JS file execution failure.
Bug we were experiencing is a known one. Applied patch to fix it.
* If you want to see the bug in action, first do this:
*  `git checkout origin/dev`
* `make fresh` if necessary
Now, while you're in dev branch, go to: https://drupal-infofinland.docker.so/en/node/add/page. Open the console and you should see an error:
```
Uncaught DOMException: DOMTokenList.remove: The token can not contain whitespace.
```
To apply the fix:
* `git checkout origin/UHF-10654-fix-yoast-error`
* `make shell` into the container
* Run `composer install`. You should see the patch getting applied
... OR just …

UHF-10654: Apply patch to fix yoast errors

---

docker/openshift/crons/base.sh
docker/openshift/crons/purge-copied-paragraphs.sh
public/modules/custom/infofinland_common/infofinland_common.module
public/modules/custom/infofinland_common/src/Plugin/QueueWorker/ParagraphCopyWorker.php

Prevent page save from dying by moving the paragraph-copier to queue
Created queue to handle paragraph copying between translations.
* `git checkout UHF-10742`
* `make fresh`
Try coming up with different ways to break the feature here's a few.
Few things about the copy-feature:
- The copying only directly affects the paragraphs which were added to finnish node
- If paragraphs were added to translations, the copying tool won't be able to take them into account.
- The copied paragraphs try to follow the finnish translation as closely as possible. 
Notice: **Pay attention to the total count of added and copied paragraphs. The old implementation might have had a bug which causes data loss.**
- Create new page …

UHF-10742 paragraph copier

---

composer.json
patches/gin_row_weights-3461093.patch

* Added patch to fix the 'show row weights' button when dealing with paragraphs.
* `git checkout UHF-10657`
* `make fresh`
[UHF-10657]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10657: Show row weights

---

phpstan.neon
public/modules/custom/infofinland_common/infofinland_common.install
public/modules/custom/infofinland_common/infofinland_common.services.yml
public/modules/custom/infofinland_common/src/Plugin/QueueWorker/ParagraphCopyWorker.php

- Prevent the error that can be found from cron pod (mentioned below).
- Update hook to recreate the missing revisions for node 39828
* `git checkout UHF-11298`
* `make fresh`
- Go and edit en and sv translations of node 39828
- Edit page should load normally
- Saving the node works
Also
Check that the added check to ParagraphCopyWorker on line 91 prevents the worker from dying:
**Original error:** Error: Call to a member function getTranslation() on null in Drupal\infofinland_common\Plugin\QueueWorker\ParagraphCopyWorker->processItem() (line 91 of /var/www/html/public/modules/custom/infofinland_common/src/Plugin/QueueWorker/ParagraphCopyWorker.php) 
[UHF-11298]: …

node_translation not existing caused error

---

composer.lock
phpstan.neon
public/modules/custom/infofinland_permissions/infofinland_permissions.module

User 52 would not be able to see linkkipankki when the user was connected to municipality id 7 (vaasa).
If user had municipality 7, the array diff would return [0 => ""], which caused 304.
If instead of [0 => ""] you would return [], the view would be empty but would render normally
If you would return [7], it would exclude all id 7 -links from the view.
If you return all allowed values [1,2,3,4,7], it shows all links and user may edit the links belonging under ID-7
Fix this by just showing all links for all users. Only user with proper municipality is allowed to edit the links.
* `git checkout UHF-11392`
* `make fresh`
- (You might want to login as admin and in incognito window user id 52.)
- Login as …

UHF-11392: Linkkipankki permission problem

---

conf/cmi/core.extension.yml
public/modules/custom/infofinland_config/config/rewrite/editor.editor.full_html.yml
public/modules/custom/infofinland_config/config/rewrite/filter.format.full_html.yml
public/modules/custom/infofinland_config/infofinland_config.info.yml

* Added and enabled Infofinland Config module to override default configurations.
* `git checkout UHF-11171`
* `make fresh`
[UHF-11171]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11171: Infofinland config overrides
