conf/cmi/system.menu.footer-bottom-navigation.yml
conf/cmi/system.menu.sosiaalisen-median-navigaatio.yml

Run drush cim -y to get the new conf
Check that you have alatunniste navigation and social media menu present

IFU-328: Footer nav and social media nav

---

conf/cmi/block.block.infofinlandmunicipalityselectionblock.yml
conf/cmi/core.extension.yml
conf/cmi/language.content_settings.taxonomy_term.municipalitys.yml
conf/cmi/system.menu.main.yml
conf/cmi/taxonomy.vocabulary.municipalitys.yml
public/modules/custom/infofinland_municipality_selection/README.md
public/modules/custom/infofinland_municipality_selection/infofinland_municipality_selection.info.yml
public/modules/custom/infofinland_municipality_selection/infofinland_municipality_selection.routing.yml
public/modules/custom/infofinland_municipality_selection/src/Form/InfofinlandMunicipalitySelectionBlockForm.php
public/modules/custom/infofinland_municipality_selection/src/Plugin/Block/InfofinlandMunicipalitySelectionBlock.php
public/themes/custom/infofinland/infofinland.theme
public/themes/custom/infofinland/templates/layout/page.html.twig

How to check
1. Check that you have a taxonomy called kunnat
2. Check that infofinland municipality select module is enabled
3. check that the module block is in use
4. Select municipality from a dropdown from some page
5. check that the selected county comes up in h1 element

IFU-333: Added new module

---

conf/cmi/core.base_field_override.node.message.promote.yml
conf/cmi/core.entity_form_display.node.landing_page.default.yml
conf/cmi/core.entity_form_display.node.message.default.yml
conf/cmi/core.entity_form_display.node.page.default.yml
conf/cmi/core.entity_view_display.node.message.default.yml
conf/cmi/core.entity_view_display.node.message.teaser.yml
conf/cmi/core.entity_view_display.node.page.default.yml
conf/cmi/core.entity_view_display.node.page.teaser.yml
conf/cmi/editor.editor.simple_html.yml
conf/cmi/field.field.node.message.body.yml
conf/cmi/field.field.node.message.field_message_type.yml
conf/cmi/field.field.node.message.field_page.yml
conf/cmi/field.field.node.page.field_theme_menu.yml
conf/cmi/field.storage.node.field_message_type.yml
conf/cmi/field.storage.node.field_page.yml
conf/cmi/field.storage.node.field_theme_menu.yml
conf/cmi/language.content_settings.node.message.yml
conf/cmi/node.type.message.yml
conf/cmi/user.role.admin.yml
conf/cmi/user.role.infofinland_user.yml
conf/cmi/views.view.content.yml
public/modules/custom/infofinland_common/infofinland_common.module

Add theme menu to basic page.
Add new content type: Message.

IFU-529: Share content messages

---

composer.json
conf/cmi/redirect.settings.yml
conf/cmi/webform.webform.contact.yml
public/modules/custom/infofinland_common/infofinland_common.links.task.yml
public/modules/custom/infofinland_common/infofinland_common.module

Configs changes.
Fix draft workflow.
Remove publish all translation button until it works better.

Config changes

---

composer.json

Add patch for optimizing saving node with translations and content moderation.

Add patch for optimizing saving node

---

composer.json
composer.lock

Security update for Drupal and dependencies (last 9.3 version)
Purge module also updated to latest version
No DB updates to be executed

PLATTA-4199 - Drupal upgraded to latest 9.3

---

composer.json
composer.lock
conf/cmi/next.next_entity_type_config.node.landing_page.yml
conf/cmi/user.role.anonymous.yml

Add revalidation settings for landing page
Add missing permission
Update next module to version 1.4

Add revalidation settings

---

conf/cmi/language.entity.so.yml
conf/cmi/language.negotiation.yml
conf/cmi/next.next_entity_type_config.node.link.yml
conf/cmi/next.next_entity_type_config.node.message.yml

Remove somali language
Add revalidation settings for link and message

IFU-X: remove somali language

---

conf/cmi/views.view.content.yml

Changed /admin/content view to show the author of the last revision.

IFU-726: use last updated by in content view

---

conf/cmi/views.view.content.yml
public/sites/default/settings.php

Changed language rendering of the Content View to show rows in original language.
Test by visiting the content listing page to verify that the rows are rendered in the correct language.

IFU-869 - Fixed language rendering on Content View

---

public/sites/default/env.indicator.settings.php

Check the code/file that the syntax errors have been fixed.

IFU-792: Fixed syntax error on the code

---

composer.json
composer.lock
conf/cmi/core.extension.yml
conf/cmi/filter.format.full_html.yml
conf/cmi/filter.format.simple_html.yml
conf/cmi/obfuscate.settings.yml

First run the following commands, `drush cr` , `composer install`, `drush cr` and `drush cim `. Might need to run `cr` after the `cim`.
I installed and enabled the obfuscate module. So it should make sure, that the email addresses get obfuscated on the source code, on the UI, it should have those @-characters, but when you look up the source code, it should be like scrambled eggs.
Side note: I don't really like the idea, that we have two open PR's and both of them include changes to `composer.json`. That usually causes conflicts.

IFU-865: Installed and enabled the obfuscate module.

---

conf/cmi/filter.format.full_html.yml
conf/cmi/filter.format.plain_text.yml
conf/cmi/filter.format.simple_html.yml

To test:
Pick some page, e.g. Accessibility. Try out the links. Also look around and see what's broken about emails and links.
Note:
- email addresses should written as plain text WITHOUT the link function
- URLs should be created with the link button on the toolbar, or else they will be output as plain text

IFU-898 - Fixed email address obfuscation

---

conf/cmi/environment_indicator.switcher.stage.yml

There is your slash back, we are not on a guns'n roses concert.

IFU-893: hotfix/IFU-893: Added that missing slash

---

composer.json
composer.lock

Most of the required modules have already been moved to root composer.json. This one removes the platform config from root composer.json

UHF-X actual platform config remove

---

composer.json

Missing patch prevents deployment.

UHF-x apply missing linkit patch

---

README.md

* Updated step-by-step installation instructions to the readme-file.
[UHF-9686]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9686: Update readme with installation instructions

---

README.md
public/themes/custom/infofinland_admin/src/css/styles.css

Style fixes to second production deployment

Dev to main

---

conf/cmi/entity_browser.browser.media_entity_browser_modal.yml

image upload modal was wrong size. Changed the height to be responsive

set height to be responsive

---

composer.json
public/modules/custom/infofinland_admin_tools/infofinland_admin_tools.module
public/themes/custom/infofinland_admin/infofinland_admin.theme
public/themes/custom/infofinland_admin/src/templates/navigation/links--language-block.html.twig

Language fixer active link was missing
* `git checkout UHF-X_language_switcher`
* `make fresh`
Go to edit any content with any language
The language switcher should bold the current language

Language switcher fix

---

public/modules/custom/helfi_ckeditor/helfi_ckeditor.module

Adds additional check to prevent notice/error on some occasions

Release 2024-04-09 hotfix

---

.github/workflows/npm-audit.yml

* Added npm audit workflow.
[UHF-9921]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9921: Added npm audit workflow.

---

public/modules/custom/infofinland_common/infofinland_common.info.yml

* Fix artifact generation: https://github.com/City-of-Helsinki/drupal-infofinland/actions/runs/8798518141

UHF-X: Fix artifact generation

---

conf/cmi/helfi_api_base.features.yml

Enable email sending

---

public/modules/custom/infofinland_common/src/Controller/OAuth2TokenController.php
public/modules/custom/infofinland_common/tests/src/Kernel/OAuth2TokenControllerTest.php

Fixed frontend
* `git checkout UHF-0000_insert_correct_branch`
* `make fresh`
* Setup Infofinland-ui, check the readme.md for instructions
Once both backend and frontend are running, go to localhost:3000
Page should load normally

UHF-10603: frontend fix

---

public/modules/custom/infofinland_common/infofinland_common.module

This reverts commit 3775f1288b351010affd916a5230f1ad29f06378.

Revert "UHF-10618: Disable paragraph duplication for now"

---

composer.json
composer.lock
conf/cmi/block.block.claro_help.yml
conf/cmi/block.block.gin_help.yml
conf/cmi/core.extension.yml

Enabled help_topics to prevent the errors in sentry
purge must be in root composer.json since proxy module is not present

UHF-X modules

---

docker/openshift/crons/base.sh

Typo in cron base.sh

---

composer.json
composer.lock
patches/gin-3460390-sidebar-nextsibling-innerhtml-rc13.patch

* Added patch for the gin sidebar issue. See: https://www.drupal.org/project/gin/issues/3460390
* `git checkout UHF-10892`
* `make fresh`
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/306
[UHF-10892]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10892 Gin sidebar

---

public/themes/custom/infofinland/infofinland.theme

[UHF-10444]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10444: Theme tfa_entry_form

---

composer.json
composer.lock

* Updated Gin theme to latest version with dependencies.
* Removed patches that are no longer valid.
* Updated Drupal core.
* `git checkout UHF-X_update_gin`
* `make fresh`

UHF-X: Update Gin theme

---

composer.json
composer.lock

Updated Gin to 4.0

---

composer.lock
conf/cmi/editor.editor.minimal.yml
conf/cmi/encrypt.profile.real_aes.yml
conf/cmi/filter.format.minimal.yml
conf/cmi/language/fi/filter.format.full_html.yml
conf/cmi/language/fi/filter.format.minimal.yml
conf/cmi/language/sv/filter.format.full_html.yml
conf/cmi/language/sv/filter.format.minimal.yml
conf/cmi/user.role.content_producer.yml
conf/cmi/user.role.editor.yml
docker/elastic-proxy/nginx.conf

- Updated active configuration.
- Updated platform

Automatic update

---

conf/cmi/core.extension.yml

* Infofinland has no use for these modules. 
[UHF-11545]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11545: Remove big_pipe & page_cache

---

.github/workflows/test.yml
sonar-project.properties

[UHF-11404]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11404: Add sonarcloud properties
